name: Run Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/FSharp.FIO.sln

      - name: Build
        run: dotnet build --no-restore src/FSharp.FIO.sln

      - name: Run tests
        run: dotnet test --no-build --verbosity normal src/FSharp.FIO.sln
